import { app } from 'electron';
import { ipcMain } from './bus';
import * as fs from 'fs';
import * as datasets from '../data/datasets';
import * as datasetView from '../engine/datasetView';
import * as duck from '../engine/duckdb';

// Mosaic database connector over Electron IPC — MAIN PROCESS.
//
// Mosaic's ENTIRE database contract is one method:
//
//   query(q: {type?: 'arrow'|'exec'|'json', sql: string})
//     => Promise<Table | void | Record<string, unknown>[]>
//
// which maps onto `ipcRenderer.invoke` directly (docs/phase-3/README.md §2). Two
// channels implement it:
//
//   mosaic:view  (projectId, datasetId) → the TYPED, USER-NAMED view to query
//   mosaic:query ({sql, type})          → run one statement, return JSON rows
//
// ── ARROW IS IMPOSSIBLE, AND SAYING SO IS THE POINT ──────────────────────────
// `@duckdb/node-api` ships NO Arrow support (every Arrow binding in its .d.ts is
// commented out — src/duckdb.ts, phase-1). So `type: 'arrow'` is REJECTED with an
// explicit error rather than silently downgraded to JSON. A silent downgrade is
// exactly the failure docs/phase-3/README.md recorded: Mosaic's Coordinator
// consolidation calls a flechette-only `data.select`, and a blank chart with
// `TypeError: data.select is not a function` is the only diagnostic the user
// gets. The renderer must construct the Coordinator with `{ consolidate: false }`
// and take the JSON path; an error here says so out loud.
//
// ── EVERY CALL USES queryAsync/execAsync. NEVER query/exec ────────────────────
// The sync bridge blocks the Electron MAIN THREAD on `Atomics.wait` — measured at
// 0 event-loop ticks for the duration of the call (docs/phase-3b §1). Mosaic
// issues queries at animation-frame rate, so a sync call here would freeze all
// five windows, the menu bar and the global hotkey on every frame of a brush
// drag. That is blocker B3, and phase 3b exists to make this file possible.
// `scripts/test-mosaicIpc.ts` proves it by replacing `duckdb.query`/`exec` with
// throwing stubs and running the whole surface against them.
//
// One consequence worth stating: `ensureHardened()` runs FIRST in both handlers,
// and it uses `execAsync`, which starts the worker through the non-blocking
// handshake. By the time `datasets.residentSource` reaches the synchronous
// `duck.isAvailable()` probe the bridge is already 'ready', so that probe returns
// without ever entering `Atomics.wait`. Reordering those two calls would
// re-introduce a ~115 ms main-thread freeze on the first Mosaic query.
//
// ═════════════════════════════════════════════════════════════════════════════
// SECURITY — what was measured, what was applied, and what is still possible
// ═════════════════════════════════════════════════════════════════════════════
//
// THE FACT THIS SECTION EXISTS FOR, re-verified on this build (DuckDB v1.5.5,
// `@duckdb/node-api`), not taken on trust:
//
//   duck.query('SELECT 1 AS one; DROP VIEW sentinel;')  →  [] , and the sentinel
//   view is GONE ("Catalog Error: Table with name sentinel does not exist!").
//   duck.query("SELECT 'first' AS v; SELECT 'second' AS v;")  →  [{v:'second'}]
//
// MULTI-STATEMENT SQL EXECUTES. The binding does not reject it, and only the LAST
// statement's rows come back — so a second statement can run completely
// invisibly. Anything that treats `query(sql)` as "one statement" is wrong.
//
// ── The trust boundary, stated honestly ──────────────────────────────────────
// The hub renderer runs with `contextIsolation: true`, `nodeIntegration: false`,
// and a CSP of `script-src 'self'` with no inline script and no eval. The SQL
// arriving on `mosaic:query` is generated by Mosaic — app code — so under normal
// operation it is app-authored, not user-authored. A compromised renderer is the
// only threat model in which hostile SQL reaches this channel.
//
// But that threat is not empty, because DuckDB is not merely a calculator: it can
// READ AND WRITE THE FILESYSTEM (`read_csv`, `COPY … TO`), ATTACH databases, and
// INSTALL/LOAD extensions — which is native code execution. Those are a genuine
// escalation beyond the rest of the hub IPC surface, so they get a real control,
// not a comment.
//
// ── CONTROL 1 (the strong one): the engine is locked down ────────────────────
// Applied once, lazily, on the first Mosaic call — `hardenConnection()`:
//
//   SET allowed_directories=['<userData>'];   -- MUST come first (see below)
//   SET enable_external_access=false;
//   SET lock_configuration=true;
//
// Measured on this build, AFTER those three:
//
//   read_csv('/etc/hosts')          Permission Error: Cannot access file … -
//                                   file system operations are disabled by
//                                   configuration
//   COPY (SELECT 1) TO '/tmp/x.csv' Permission Error (same)
//   INSTALL httpfs                  Permission Error (cannot reach the ext dir)
//   LOAD httpfs                     Permission Error: Loading external extensions
//                                   is disabled through configuration
//   ATTACH '/tmp/x.db'              Permission Error (same)
//   SET enable_external_access=true Invalid Input Error: … the configuration has
//                                   been locked
//   read_parquet('<userData>/…')    STILL WORKS  ← the app is unaffected
//   COPY … TO '<userData>/…'        STILL WORKS  ← parquetStore still writes
//
// THE ORDER IS LOAD-BEARING AND IS NOT OBVIOUS. `allowed_directories` must be set
// while external access is still ENABLED: afterwards DuckDB refuses with
// "Cannot change allowed_directories when enable_external_access is disabled".
// Set it the other way round (allowed_directories, then lock, WITHOUT disabling
// external access) and it enforces NOTHING — measured: `/etc/hosts`, `COPY TO
// /tmp`, `INSTALL httpfs` and `ATTACH` all still succeed. An allow-list that
// looks applied and enforces nothing is worse than none, so it is pinned by a
// test.
//
// `allowed_directories` IS recursive (a file three levels below the root reads
// fine), DuckDB canonicalises it itself (`/var/…` was stored as `/private/var/…`),
// and a `..` in a path does not escape it — all measured.
//
// Two settings deliberately NOT applied, because measurement says they buy
// nothing here: `allow_unsigned_extensions=false` and
// `autoload_known_extensions=false` are redundant once `LOAD` itself is a
// Permission Error, and `SET disabled_filesystems='LocalFileSystem'` DOES work
// but also kills `read_parquet` on our own files — it takes the whole app down
// with it. Listing no-op SETs would only manufacture confidence.
//
// BLAST RADIUS, stated plainly: there is ONE DuckDB connection for the whole
// process, so this hardening applies to `residentQuery`, `statsResident`,
// `parquetStore`, `pipelineDuck` and everything else, and `lock_configuration` is
// IRREVERSIBLE for the life of the process ("Cannot enable external access while
// database is running"). That is safe today because every DuckDB file access in
// this app is under `userData` (Parquet tables plus the temp siblings
// `parquetStore.writeTable` writes NEXT TO the target). A future feature that
// wants DuckDB to read a user-picked file OUTSIDE `userData` — `read_csv` on a
// path from the open dialog, say — would have to add that directory to
// `MOSAIC_ALLOWED_DIRS` BEFORE the first Mosaic call, or it will fail with a
// Permission Error. CSV/XLSX parsing today is pure JS and never touches DuckDB.
//
// If hardening FAILS, the channels still serve queries and `hardeningState()`
// reports the failure. Refusing to answer would take the feature down over a
// control that guards against a renderer compromise which, if it happened, would
// already own the rest of the hub bridge. That is a judgement call and it is
// recorded here rather than hidden.
//
// ── CONTROL 2 (defence in depth): one statement per call ─────────────────────
// `isSingleStatement()` rejects multi-statement input at the channel boundary. It
// is a LEXER, not DuckDB's parser, and this is where overclaiming would be easy,
// so precisely:
//
//   • It models the constructs a `;` can legally hide inside, and each was
//     verified against THIS DuckDB build rather than assumed: `'…'` with `''`
//     doubling; `E'…'`/`e'…'` with backslash escapes (a backslash in a PLAIN
//     string is literal — measured); `"…"` identifiers with `""` doubling;
//     `$$…$$` and `$tag$…$tag$` dollar quoting; `--` line comments; and `/* … */`
//     block comments, WHICH NEST on this build (measured: `/* a /* b */ c */` is
//     one comment).
//   • It FAILS CLOSED. A construct it fails to model can only make it think a
//     quoted region ended early, which yields a REJECTION of valid SQL — never a
//     bypass. A bypass would require the lexer to believe it is inside a quote
//     where DuckDB believes it is not, which is why every quoting form above was
//     measured rather than guessed. Input that ends inside an unterminated quote
//     or comment is rejected too.
//   • It is NOT airtight, and it is not claimed to be. A DuckDB quoting syntax
//     that exists and is not listed above would be a hole. What makes this
//     acceptable is that it is the SECOND control: the engine lock above does not
//     depend on parsing SQL correctly at all.
//
// DELIBERATELY NOT DONE: gating on statement KIND. `type: 'exec'` is a
// side-effect channel by contract (Mosaic uses it for temp tables and cached
// indexes), so a keyword allow-list on the `query` path would stop nothing an
// attacker could not do by flipping `type` to `'exec'`, while breaking legitimate
// Mosaic SQL. The DuckDB CATALOG is not a trust boundary here: it is an in-memory
// `:memory:` catalog of views over files. Dropping a view costs a
// `CREATE OR REPLACE`, not data — every byte the app owns is in Parquet and JSON
// on disk, which the engine lock protects.
//
// ── WHAT REMAINS POSSIBLE, with hardening applied ────────────────────────────
// A compromised renderer can still, through this channel:
//   • read any dataset in ANY project of this app (`read_parquet` under userData
//     is allowed by design — that is the feature), and write files anywhere under
//     `userData` via `COPY … TO`;
//   • create, replace and drop views and tables in the in-memory catalog;
//   • run an arbitrarily expensive query. There is no statement timeout on the
//     DuckDB side; the bridge's 120 s call ceiling and 512 MiB payload ceiling are
//     the only bounds, so a hostile query is a denial-of-service, not a leak.
// It can NOT read or write outside `userData`, load an extension, attach another
// database, or reach the network.

// ── Constants ────────────────────────────────────────────────────────────────

/**
 * Ids arrive from the renderer over IPC. Validate the SHAPE before either id
 * reaches a filesystem path or a SQL identifier. Copied verbatim from
 * `src/datasets.ts` (which keeps it module-private), exactly as
 * `src/ipc/dashboardExport.ts` does.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function isValidId(id: unknown): id is string {
  return typeof id === 'string' && UUID_RE.test(id);
}

/**
 * Rows returned to the renderer in one `mosaic:query` reply.
 *
 * This is an IPC-PAYLOAD bound, not a memory bound, and the difference is worth
 * being honest about: the full result has already crossed the worker→main bridge
 * (bounded there by its own 512 MiB ceiling) before this cap is applied. What the
 * cap prevents is handing a multi-million-row array to `structuredClone` for the
 * renderer, which is where a big result actually hurts. Mosaic's aggregated
 * queries return one row per mark, so this is a backstop for a hand-written or
 * hostile query, not something normal use approaches.
 *
 * Truncation is REPORTED (`truncated: true` plus the real `rowCount`), never
 * silent — a chart drawn from a silently trimmed result is a wrong chart.
 */
export const MAX_QUERY_ROWS = 100_000;

// ── Public shapes ────────────────────────────────────────────────────────────

export interface MosaicViewColumn {
  /** The identifier the view exposes — from `viewColumns()`, never `DESCRIBE`. */
  name: string;
  /** Ordinate's declared `ColumnType`: 'text' | 'number' | 'date'. */
  type: string;
  /** What `DESCRIBE` would report, so a scale can be chosen without a round trip. */
  sqlType: 'DOUBLE' | 'VARCHAR';
}

export type MosaicViewResult =
  | { ok: true; name: string; columns: MosaicViewColumn[] }
  | { ok: false; error: string };

export type MosaicQueryResult =
  | { ok: true; rows: duck.DuckRow[]; rowCount: number; truncated: boolean }
  | { ok: false; error: string };

export interface HardeningState {
  /** True once `hardenConnection` has run to completion (successfully or not). */
  attempted: boolean;
  /** True when every statement was accepted by the engine. */
  ok: boolean;
  /** The statements that were accepted, in order. */
  applied: string[];
  /** The first failure, verbatim from DuckDB, or null. */
  error: string | null;
}

// ── The view name ────────────────────────────────────────────────────────────

/**
 * `datasetView` VALIDATES view names and never constructs one, so that a raw id
 * can never become SQL text by accident; its header prescribes exactly this
 * mapping, and a UUID's hyphens are what make the mapping necessary.
 *
 * Returns null for anything that is not a UUID — so the only strings that reach
 * `viewSql` are `ds_` followed by 32 hex digits and 4 underscores.
 */
export function viewNameFor(datasetId: unknown): string | null {
  if (!isValidId(datasetId)) return null;
  const name = 'ds_' + datasetId.replace(/-/g, '_');
  return datasetView.isViewName(name) ? name : null;
}

// ── CONTROL 2 — one statement per call ───────────────────────────────────────

/**
 * The number of statements in `sql`, or -1 when the input ends inside an
 * unterminated string/identifier/comment (malformed — DuckDB would reject it
 * anyway, and guessing about it is exactly how a lexer gate becomes a hole).
 *
 * Empty statements do not count, so `';;SELECT 1;;'` is 1 — measured, DuckDB
 * accepts leading and repeated semicolons.
 *
 * See the SECURITY section above for what this does and does not guarantee. In
 * one line: it fails closed, and it is the second control, not the first.
 */
export function statementCount(sql: string): number {
  if (typeof sql !== 'string') return -1;

  let count = 0;
  let hasContent = false; // any non-whitespace since the last top-level `;`
  let i = 0;
  const n = sql.length;

  while (i < n) {
    const ch = sql[i];

    // ── Line comment: `-- … <newline>` ──
    if (ch === '-' && sql[i + 1] === '-') {
      i += 2;
      while (i < n && sql[i] !== '\n') i += 1;
      continue;
    }

    // ── Block comment: `/* … */`, NESTING (measured on this build) ──
    if (ch === '/' && sql[i + 1] === '*') {
      let depth = 1;
      i += 2;
      while (i < n && depth > 0) {
        if (sql[i] === '/' && sql[i + 1] === '*') {
          depth += 1;
          i += 2;
        } else if (sql[i] === '*' && sql[i + 1] === '/') {
          depth -= 1;
          i += 2;
        } else i += 1;
      }
      if (depth > 0) return -1; // unterminated
      continue;
    }

    // ── String literal: `'…'`, `''` doubling; backslash escapes ONLY after an
    //    E/e prefix (measured: a backslash in a PLAIN string is literal). ──
    if (ch === "'") {
      const prev = i > 0 ? sql[i - 1] : '';
      const beforePrev = i > 1 ? sql[i - 2] : '';
      const escaped = (prev === 'e' || prev === 'E') && !/[A-Za-z0-9_$]/.test(beforePrev);
      i += 1;
      let closed = false;
      while (i < n) {
        if (escaped && sql[i] === '\\') {
          i += 2;
          continue;
        }
        if (sql[i] === "'") {
          if (sql[i + 1] === "'") {
            i += 2;
            continue;
          }
          i += 1;
          closed = true;
          break;
        }
        i += 1;
      }
      if (!closed) return -1;
      hasContent = true;
      continue;
    }

    // ── Quoted identifier: `"…"`, `""` doubling ──
    if (ch === '"') {
      i += 1;
      let closed = false;
      while (i < n) {
        if (sql[i] === '"') {
          if (sql[i + 1] === '"') {
            i += 2;
            continue;
          }
          i += 1;
          closed = true;
          break;
        }
        i += 1;
      }
      if (!closed) return -1;
      hasContent = true;
      continue;
    }

    // ── Dollar quoting: `$$…$$` / `$tag$…$tag$` (both measured to work) ──
    if (ch === '$') {
      const open = /^\$([A-Za-z_][A-Za-z0-9_]*)?\$/.exec(sql.slice(i));
      if (open) {
        const delim = open[0];
        const end = sql.indexOf(delim, i + delim.length);
        if (end < 0) return -1; // unterminated
        i = end + delim.length;
        hasContent = true;
        continue;
      }
      // A bare `$1`/`$name` parameter reference — ordinary content.
    }

    // ── A top-level statement separator ──
    if (ch === ';') {
      if (hasContent) count += 1;
      hasContent = false;
      i += 1;
      continue;
    }

    if (!/\s/.test(ch)) hasContent = true;
    i += 1;
  }

  if (hasContent) count += 1;
  return count;
}

/** True when `sql` is exactly one well-formed-enough statement. Fails closed. */
export function isSingleStatement(sql: string): boolean {
  return statementCount(sql) === 1;
}

// ── CONTROL 1 — engine hardening ─────────────────────────────────────────────

let hardening: Promise<HardeningState> | null = null;
let state: HardeningState = { attempted: false, ok: false, applied: [], error: null };

/** The outcome of `hardenConnection`, for diagnostics and tests. */
export function hardeningState(): HardeningState {
  return { ...state, applied: [...state.applied] };
}

/** Test-only: forget that hardening ran. The ENGINE cannot be un-hardened. */
export function resetHardeningForTests(): void {
  hardening = null;
  state = { attempted: false, ok: false, applied: [], error: null };
}

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/**
 * Lock the shared DuckDB connection down to `allowedDirs`, once per process.
 *
 * ORDER IS LOAD-BEARING — see the SECURITY section. `allowed_directories` must be
 * set BEFORE external access is disabled (DuckDB refuses it afterwards), and
 * disabling external access is what makes the allow-list mean anything at all.
 *
 * Never throws, and never rejects: a failure is recorded in `hardeningState()`
 * and the caller proceeds. Idempotent — concurrent callers share one promise, and
 * a second call after it settled is a no-op.
 */
export function hardenConnection(allowedDirs: readonly string[]): Promise<HardeningState> {
  if (hardening) return hardening;
  hardening = (async (): Promise<HardeningState> => {
    const applied: string[] = [];
    let error: string | null = null;
    try {
      // DuckDB canonicalises the path itself, but resolve symlinks here anyway so
      // the list we RECORD is the list the engine enforces (macOS `/var` is a
      // symlink to `/private/var`, and every temp dir lives under it).
      const dirs: string[] = [];
      for (const d of allowedDirs) {
        if (typeof d !== 'string' || !d) continue;
        try {
          fs.mkdirSync(d, { recursive: true });
          dirs.push(fs.realpathSync(d));
        } catch {
          dirs.push(d);
        }
      }
      const statements = dirs.length
        ? [
            `SET allowed_directories=[${dirs.map(sqlStr).join(', ')}];`,
            'SET enable_external_access=false;',
            'SET lock_configuration=true;',
          ]
        : // With no allow-list, disabling external access would break the app's
          // own `read_parquet`. Better to apply nothing and say so than to ship a
          // half-lock nobody can reason about.
          [];
      if (!statements.length) error = 'no allowed directories were resolved; the engine was left unhardened';
      for (const s of statements) {
        await duck.execAsync(s);
        applied.push(s);
      }
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
    }
    state = { attempted: true, ok: error === null && applied.length > 0, applied, error };
    return hardeningState();
  })();
  return hardening;
}

/**
 * The directories DuckDB is allowed to touch. `userData` holds every Parquet
 * table and every temp sibling `parquetStore.writeTable` publishes from, so it is
 * the whole surface the app needs.
 */
function appAllowedDirs(): string[] {
  try {
    return [app.getPath('userData')];
  } catch {
    return [];
  }
}

let allowedDirs: string[] | null = null;

/** Harden on first use, so nothing here costs anything until Mosaic is opened. */
async function ensureHardened(): Promise<void> {
  if (!allowedDirs) allowedDirs = appAllowedDirs();
  await hardenConnection(allowedDirs);
}

/** Test hook: choose the allow-list before the first call hardens the engine. */
export function setAllowedDirsForTests(dirs: string[]): void {
  allowedDirs = dirs;
}

// ── mosaic:view ──────────────────────────────────────────────────────────────

/**
 * Ensure the typed, user-named view over a dataset's stored Parquet, and report
 * the columns it exposes.
 *
 * NEVER HYDRATES THE TABLE. `datasets.residentSource` reads the small JSON record
 * and hands back a path plus `ParsedColumn[]`; the rows stay on disk.
 *
 * ── The cache decision: THERE IS NO CACHE, and that is deliberate ────────────
 * A dataset's Parquet is rewritten whenever its rows or its prepare steps change,
 * and the column list can change SHAPE with it (a `drop_column` or a
 * `group_aggregate` step rewrites the schema), so a stale view is not slow — it
 * is WRONG, silently, with the old columns.
 *
 * The alternative to correctness-by-construction would be a key, and the honest
 * candidates are weak: `updatedAt` is millisecond-resolution and two writes can
 * share a millisecond; the Parquet's `mtime`+`size` is closer to the truth but
 * still a proxy for content, and it costs a `stat` on every call.
 *
 * So the question became "what does not caching actually cost", and it was
 * measured rather than argued. `CREATE OR REPLACE VIEW` over a 200,000-row ×
 * 20-column Parquet, through `execAsync`: median 4.78 ms, against a 4.41 ms
 * median for a trivial `SELECT 1` on the same path. The DDL itself is ~0.4 ms —
 * the rest is the bridge round trip that any cache-validity check would also pay.
 * And `mosaic:view` is called once when a chart is set up, not once per frame:
 * the per-frame path is `mosaic:query` against the view that already exists.
 *
 * Paying 0.4 ms to be unconditionally right is the whole trade. `CREATE OR
 * REPLACE` is idempotent, so repeated calls converge on the same view.
 */
export async function resolveView(projectId: unknown, datasetId: unknown): Promise<MosaicViewResult> {
  try {
    // Both ids are UUID-validated BEFORE either reaches a path or a SQL
    // identifier — the dual-UUID guard `datasets.ts` documents.
    if (!isValidId(projectId)) return { ok: false, error: 'Invalid project id' };
    const name = viewNameFor(datasetId);
    if (!name) return { ok: false, error: 'Invalid dataset id' };

    // Before residentSource: `ensureHardened` starts the worker through the
    // NON-BLOCKING handshake, so the synchronous `duck.isAvailable()` probe
    // inside `residentSource` finds a ready bridge and never blocks. See the
    // header.
    await ensureHardened();

    const src = await datasets.residentSource(projectId, datasetId as string);
    if (!src) {
      return {
        ok: false,
        error: 'This dataset has no Parquet table to query (it may predate Parquet storage, or DuckDB is unavailable)',
      };
    }

    // `viewSql` is pure and throws on an unusable spec; `execAsync` is the
    // non-blocking twin of the `ensureView` this deliberately does not call.
    await duck.execAsync(datasetView.viewSql({ name, parquetPath: src.parquetPath, columns: src.columns }));

    // Columns come from `viewColumns()`, NOT from `DESCRIBE`. A leading U+FEFF in
    // a column name survives into the view but is LOST on `DESCRIBE` read-back
    // (an upstream `@duckdb/node-api` transport bug — docs/phase-3b §3), so a
    // `DESCRIBE`-derived identifier would fail to bind against the very view it
    // came from. `viewColumns()` is the single source of truth by contract.
    const columns: MosaicViewColumn[] = datasetView.viewColumns(src.columns).map((c) => ({
      name: c.name,
      type: c.type,
      // Mirrors `datasetView`'s projection: only a DECLARED `number` is cast.
      sqlType: c.type === 'number' ? 'DOUBLE' : 'VARCHAR',
    }));

    return { ok: true, name, columns };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Could not prepare the dataset view' };
  }
}

// ── mosaic:query ─────────────────────────────────────────────────────────────

/**
 * Run ONE statement on the shared connection and return plain JSON rows.
 *
 * `type: 'exec'` runs for side effects and resolves `{ok:true, rows: []}`;
 * `type: 'arrow'` is refused (see the header); anything else runs as a query.
 * Both paths are ASYNC — a sync call here would freeze the whole app per frame.
 */
export async function runQuery(sql: unknown, type?: unknown): Promise<MosaicQueryResult> {
  try {
    if (typeof sql !== 'string' || sql.trim() === '') {
      return { ok: false, error: 'sql must be a non-empty string' };
    }
    if (type !== undefined && type !== null && type !== 'json' && type !== 'exec' && type !== 'arrow') {
      return { ok: false, error: `Unsupported query type ${JSON.stringify(type)} (expected 'json' or 'exec')` };
    }
    // Explicit, never a silent downgrade. `@duckdb/node-api` ships no Arrow
    // support at all, so a caller asking for Arrow has mis-configured its
    // Coordinator (it needs `{ consolidate: false }`) and needs to be told, not
    // handed JSON that its consolidation path will choke on.
    if (type === 'arrow') {
      return {
        ok: false,
        error:
          'Arrow is not available: @duckdb/node-api ships no Arrow support. ' +
          "Construct the Mosaic Coordinator with { consolidate: false } so it requests type 'json'.",
      };
    }
    const count = statementCount(sql);
    if (count !== 1) {
      return {
        ok: false,
        error:
          count < 0
            ? 'Rejected: the SQL ends inside an unterminated string, identifier or comment'
            : `Rejected: expected exactly one SQL statement, found ${count}`,
      };
    }

    await ensureHardened();

    if (type === 'exec') {
      await duck.execAsync(sql);
      return { ok: true, rows: [], rowCount: 0, truncated: false };
    }

    const rows = await duck.queryAsync(sql);
    if (rows.length > MAX_QUERY_ROWS) {
      // Reported, never silent — see MAX_QUERY_ROWS.
      return { ok: true, rows: rows.slice(0, MAX_QUERY_ROWS), rowCount: rows.length, truncated: true };
    }
    return { ok: true, rows, rowCount: rows.length, truncated: false };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Query failed' };
  }
}

// ── Registration ─────────────────────────────────────────────────────────────

export function register() {
  ipcMain.handle('mosaic:view', async (_e, { projectId, datasetId }: any = {}) => resolveView(projectId, datasetId));

  ipcMain.handle('mosaic:query', async (_e, { sql, type }: any = {}) => runQuery(sql, type));
}
