// Generates web/src/ui/icons/paths.ts from the desktop hub's icon set
// (renderer/hub/icons.ts, the one hand-authored source) so the two never
// drift by hand-copying. Run after editing icons.ts:
//
//   node web/scripts/gen-icons.mjs           write paths.ts
//   node web/scripts/gen-icons.mjs --check   exit 1 if paths.ts is stale
//
// Parsed, never evaluated: every entry in ICONS is `name: '<svg body>'`
// (one single-quoted literal, no concatenation), which the regex below
// reads; a shape it cannot read is a loud failure, not a missing icon.
// After P8 deletes renderer/, paths.ts becomes the source and this goes.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SRC = fileURLToPath(new URL('../../renderer/hub/icons.ts', import.meta.url));
const OUT = fileURLToPath(new URL('../src/ui/icons/paths.ts', import.meta.url));

const src = readFileSync(SRC, 'utf8');
const block = /^const ICONS[^{]*\{([\s\S]*?)^\};/m.exec(src);
if (!block) throw new Error('gen-icons: no `const ICONS = { … };` block in renderer/hub/icons.ts');
const body = block[1].replace(/\/\*[\s\S]*?\*\//g, '');

const entries = [...body.matchAll(/^\s*'?([\w-]+)'?:\s*'([^']*)',?\s*$/gm)].map((m) => [m[1], m[2]]);
const keys = (body.match(/^\s*'?[\w-]+'?:/gm) ?? []).length;
if (entries.length !== keys || entries.length === 0) {
  throw new Error(`gen-icons: read ${entries.length} of ${keys} entries; icons.ts changed shape`);
}

const lines = entries.map(([k, v]) => `  ${/^[a-z]\w*$/i.test(k) ? k : `'${k}'`}: '${v}',`);
const out = `// GENERATED by web/scripts/gen-icons.mjs from renderer/hub/icons.ts — do not edit.
// Lucide house style: 24-unit viewBox, 1.5 stroke, round caps, currentColor;
// a FILLED glyph opts out locally with fill="currentColor" stroke="none".

export const ICON_PATHS = {
${lines.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    // missing counts as stale
  }
  if (current !== out) {
    console.error('web/src/ui/icons/paths.ts is stale: run node web/scripts/gen-icons.mjs');
    process.exit(1);
  }
  console.log(`icons: ${entries.length} in sync`);
} else {
  writeFileSync(OUT, out);
  console.log(`icons: wrote ${entries.length} to web/src/ui/icons/paths.ts`);
}
