// History persistence — MAIN PROCESS ONLY.
// Each thread is stored as userData/history/<threadId>/thread.json + crop.png.
// The Anthropic messages array (including base64 image) is stored in thread.json;
// it is the user's own data on their own machine, never transmitted anywhere.
// API keys are NEVER written here.

import * as fs from 'fs';
import * as path from 'path';
import * as appPaths from './paths';
import * as recordFs from './recordFs';

function getHistoryDir(): string {
  return path.join(appPaths.userData(), 'history');
}

// History ids are Date.now()-ish (digits, occasionally with a suffix), always
// generated by main — never a path. Reject anything with `.`/`/`/`\` (or other
// separators) so a malformed/compromised renderer id can't escape the history
// dir into an arbitrary-file read (loadThread) or recursive delete (deleteThread).
const ID_RE = /^[0-9a-zA-Z_-]+$/;
function isValidId(id: string | number): boolean {
  return ID_RE.test(String(id));
}

function threadDir(id: string | number): string {
  return path.join(getHistoryDir(), String(id));
}

function threadFilePath(id: string | number): string {
  return path.join(threadDir(id), 'thread.json');
}

function cropFilePath(id: string | number): string {
  return path.join(threadDir(id), 'crop.png');
}

// Create history directory on first run.
export async function init(): Promise<void> {
  await fs.promises.mkdir(getHistoryDir(), { recursive: true });
}

// Write the crop image (from a data URL) to disk. Returns the absolute path.
export async function saveCrop(id: string | number, dataUrl: string): Promise<string> {
  const dir = threadDir(id);
  await fs.promises.mkdir(dir, { recursive: true });
  const base64 = dataUrl.replace(/^data:image\/[^;]+;base64,/, '');
  const buf = Buffer.from(base64, 'base64');
  const p = cropFilePath(id);
  await recordFs.writeFile(p, buf);
  return p;
}

// Save (create or overwrite) a thread file.
// thread: { id, title, createdAt, updatedAt, cropPath, messages, result, turns }
// ponytail: the thread envelope carries the whole conversation JSON — not worth typing.
export async function saveThread(thread: any): Promise<void> {
  const dir = threadDir(thread.id);
  await fs.promises.mkdir(dir, { recursive: true });
  // Atomic write (temp sibling → rename): a crash mid-rewrite of an EXISTING
  // thread must never truncate thread.json (which loadThread/loadAllSummaries
  // would then skip, silently dropping a prior capture).
  const file = threadFilePath(thread.id);
  const tmp = `${file}.${Date.now()}.tmp`;
  await recordFs.writeFile(tmp, JSON.stringify(thread, null, 2), 'utf8');
  await recordFs.rename(tmp, file);
}

export interface ThreadSummary {
  id: string;
  projectId: string | null;
  title: string;
  updatedAt: string;
  cropPath: string | null;
  datasetId: string | null;
  copilotThreadId: string | null;
}

// Read every thread.json, skipping corrupt/missing files gracefully.
async function readAllThreads(): Promise<any[]> {
  const dir = getHistoryDir();
  let dirents;
  try {
    dirents = await recordFs.readdir(dir, { withFileTypes: true });
  } catch (_) {
    return [];
  }

  const threads: any[] = [];
  for (const dirent of dirents) {
    if (!dirent.isDirectory()) continue;
    const id = dirent.name;
    try {
      const raw = await recordFs.readFile(threadFilePath(id), 'utf8');
      const data = JSON.parse(raw);
      if (!data.id) continue;
      threads.push(data);
    } catch (err: any) { // ponytail: fs errors carry .code, JSON errors don't
      // ENOENT = orphaned capture (crop.png saved, thread.json never written, e.g.
      // analysis didn't finish). Not corruption — skip quietly. Only log real damage.
      if (err.code !== 'ENOENT') {
        console.error('[history] Skipping corrupt or unreadable thread:', id, err.message);
      }
    }
  }
  return threads;
}

/**
 * Adopt every pre-project capture into `projectId`.
 *
 * A capture is a project record now, but every entry written before this change
 * has no `projectId` and would be invisible under any project. One pass at
 * startup gives them the newest project (the one the user is most likely still
 * working in) and rewrites them through the same atomic saveThread.
 *
 * IDEMPOTENT: an entry that already carries a projectId is left alone, so the
 * second run finds nothing and writes nothing. Returns how many were adopted so
 * the caller can log a real number rather than "ran migration".
 */
export async function migrateProjectIds(projectId: string): Promise<number> {
  if (!projectId) return 0;
  let adopted = 0;
  for (const thread of await readAllThreads()) {
    if (thread.projectId) continue;
    thread.projectId = projectId;
    try {
      await saveThread(thread);
      adopted += 1;
    } catch (err: any) {
      console.error('[history] Could not adopt thread', thread.id, err.message);
    }
  }
  if (adopted > 0) console.log('[history] Adopted', adopted, 'pre-project capture(s) into project', projectId);
  return adopted;
}

// Return thread summaries newest-first. With a `projectId`, only that project's
// captures — a capture belongs to one project, so an unscoped list would put
// another project's screenshots in this one's Captures tab. Omit it (main's own
// crop-path cache) for every entry on disk.
export async function loadAllSummaries(projectId?: string): Promise<ThreadSummary[]> {
  const summaries: ThreadSummary[] = [];
  for (const data of await readAllThreads()) {
    if (projectId && data.projectId !== projectId) continue;
    summaries.push({
      id: data.id,
      projectId: data.projectId || null,
      title: data.title || 'Analysis',
      updatedAt: data.updatedAt || data.createdAt,
      cropPath: data.cropPath || null,
      datasetId: data.datasetId || null,
      copilotThreadId: data.copilotThreadId || null,
    });
  }
  summaries.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
  return summaries;
}

// Record which dataset a capture was saved into, so the Captures grid can badge
// it and the capture page can enable "New visual". A merge onto whatever is on
// disk — the thread may have been written by a different code path since.
export async function setDatasetId(id: string | number, datasetId: string): Promise<boolean> {
  const thread = await loadThread(id);
  if (!thread) return false;
  thread.datasetId = datasetId;
  await saveThread(thread);
  return true;
}

// Load a single thread's full data. Returns null if missing or corrupt.
// ponytail: thread envelope JSON — see saveThread.
export async function loadThread(id: string | number): Promise<any> {
  if (!isValidId(id)) return null;
  try {
    const raw = await recordFs.readFile(threadFilePath(id), 'utf8');
    return JSON.parse(raw);
  } catch (_) {
    return null;
  }
}

// Delete a thread's directory (thread.json + crop.png).
export async function deleteThread(id: string | number): Promise<boolean> {
  if (!isValidId(id)) return false;
  try {
    await recordFs.rm(threadDir(id), { recursive: true, force: true });
    return true;
  } catch (_) {
    return false;
  }
}

// Delete the ENTIRE history directory (all threads, thread.json + crop.png).
// Only ever called from an explicit, confirmed user action. Returns the dir path
// so the caller can report exactly what was removed.
export async function clearAll(): Promise<string> {
  const dir = getHistoryDir();
  await recordFs.rm(dir, { recursive: true, force: true });
  return dir;
}
