// The hub window registry (src/windows/hubRegistry.ts) — which window a push
// from main reaches once a tab can be opened in a second window.
//
// Two rules, both invisible from a single-window smoke run:
//
//   1. ONCE means the PRIMARY. A scheduled report generated by every open window
//      is the same file written twice; so `send` reaches the oldest live window
//      only, and closing it promotes the next one rather than leaving scheduled
//      work with nowhere to go.
//   2. EVERYONE means every LIVE window. A theme change or a refreshed dataset
//      must reach a secondary window too, and a destroyed window must be skipped
//      rather than thrown on.
//
// Driven with fake window objects: the registry only calls isDestroyed(),
// on('closed') and webContents.send(), and imports electron for its TYPE only,
// so it loads under plain node.
//
//   npm run build:ts && node scripts/test-hubRegistry.js

export {}; // module scope — sibling test scripts share top-level names
import { ok, finish } from './selfcheck';

import type { BrowserWindow } from 'electron';
import * as hubs from '../src/windows/hubRegistry';

// The registry is typed against BrowserWindow; the fakes stand in for the three
// members it touches, so they cross that type once, here.
const reg = {
  add: (w: Fake): unknown => hubs.add(w as unknown as BrowserWindow),
  all: (): Fake[] => hubs.all() as unknown as Fake[],
  primary: (): unknown => hubs.primary(),
  send: hubs.send,
  broadcast: hubs.broadcast,
};

interface Fake {
  name: string;
  sent: string[];
  destroyed: boolean;
  closed: Array<() => void>;
  isDestroyed(): boolean;
  on(ev: string, cb: () => void): void;
  webContents: { send(ch: string, ...args: unknown[]): void };
  close(): void;
}

function fake(name: string): Fake {
  const w: Fake = {
    name,
    sent: [],
    destroyed: false,
    closed: [],
    isDestroyed: () => w.destroyed,
    on: (ev, cb) => { if (ev === 'closed') w.closed.push(cb); },
    webContents: { send: (ch, ...args) => { w.sent.push(ch + (args.length ? ' ' + JSON.stringify(args) : '')); } },
    close: () => { w.destroyed = true; w.closed.forEach((cb) => cb()); },
  };
  return w;
}

ok('no window: primary is null, and sends go nowhere without throwing', (() => {
  if (reg.primary() !== null || reg.all().length !== 0) return false;
  reg.send('reports:run-due');
  reg.broadcast('theme:apply', { effective: 'dark' });
  return true;
})());

const a = fake('a');
const b = fake('b');
const c = fake('c');
ok('add() returns the window it was given', reg.add(a) === a);
reg.add(b);
reg.add(c);
ok('the FIRST window opened is the primary', reg.primary() === a);
ok('all() lists every live window, oldest first', reg.all().map((w) => w.name).join() === 'a,b,c');

reg.send('reports:run-due');
ok('send() reaches the primary only — scheduled work happens once',
  a.sent.join() === 'reports:run-due' && b.sent.length === 0 && c.sent.length === 0,
  JSON.stringify([a.sent, b.sent, c.sent]));

reg.broadcast('theme:apply', { effective: 'dark' });
ok('broadcast() reaches every live window, with its payload',
  [a, b, c].every((w) => w.sent[w.sent.length - 1] === 'theme:apply [{"effective":"dark"}]'));

b.destroyed = true; // destroyed but its 'closed' has not fired yet
reg.broadcast('key:changed');
ok('a destroyed window is skipped by broadcast even before it reports closed',
  b.sent.indexOf('key:changed') < 0 && a.sent.indexOf('key:changed') >= 0 && c.sent.indexOf('key:changed') >= 0);
ok('…and is not counted as live', reg.all().map((w) => w.name).join() === 'a,c');
b.close();

a.close();
ok('closing the primary promotes the next-oldest live window', reg.primary() === c);
reg.send('hub:open-settings', 'exec');
ok('…and primary-only sends follow it there', c.sent[c.sent.length - 1] === 'hub:open-settings ["exec"]'
  && a.sent.indexOf('hub:open-settings ["exec"]') < 0);

const d = fake('d');
reg.add(d);
ok('a window opened later is never primary while an older one lives', reg.primary() === c);
c.close();
ok('…until the older one closes', reg.primary() === d);
d.close();
ok('when the last window closes there is no primary again', reg.primary() === null && reg.all().length === 0);

finish();
