{{- if and .Values.pdb.enabled (or .Values.hpa.enabled (gt (int .Values.replicaCount) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ordinate.fullname" . }}
  labels:
    {{- include "ordinate.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ordinate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
